dnscrypt.h
main.c
rfc1035.c
rfc1035.h
udp_request.c
udp_request.h

The distinction between multiple questions sharing the same query identifier is currently being made using a CRC, which an attacker can predict in addition to having a very small range.
This diff replaces the CRC with SipHash, that uses a secret key and a 64 bit output.

Use the SipHash function instead of a CRC

---

cert.c

gcc/arm warns that an aggressive loop optimization can result in an undefined behavior if we access data past the end of `magic_header`.

Work around what gcc considers an undefined behavior

---

README.md
rfc1035.c
rfc1035.h
udp_request.c

Use a proper return code and store the hash in a given pointer instead.
In addition, if the packet is not a valid DNS query, I don't think ignoring the hash is the right thing to do.
Either something is broken or we're under attack, or someone is fuzzing the proxy. Either way, normal applications have no reason to try sending non-DNS queries to the proxy, so we'd better print an error and drop the packet.

Don't return a valid hash in questions_hash() to signify an error

---

dnscrypt.h
tcp_request.h
tree.h
udp_request.c
udp_request.h
version.h

The resolver response -> UDPRequest mapping currently requires traversing a linked list.
`lookup_request()` complexity is O(n) which is pretty bad as any client can easily bring down the proxy to its knee just by sending queries for random host names.
This changes the map to a red-black tree whose lookup complexity is O(log n) instead.
A simple global counter (`gen`) was added to take care of duplicates, but I think we can take this further later in order to counter dumb DoS attacks (tons of identical queries coming from the same client).

Replace the UDPRequest queue with a red-black tree

---

tcp_request.c
udp_request.c

When authoritative servers are dead or invalid, upstream resolvers can reply after the proxy timeout is reached.
This is totally expected and should not be reported as something wrong to the user.

Lower the severity of some messages

---

udp_request.c
version.h

This plugs a memory leak: the `malloc()`ed buffer for the TXT records was never released.
Since the certificate doesn't change (for now), we actually only need to call `malloc()` once.

Plug memory leak

---

udp_request.c

`self_serve_cert_file()` can only send cleartext responses.
That can be eventually fixed, but in the meantime, only call the function on unauthenticated queries.

Don't intercept TXT records for encrypted queries

---

README.md
dnscrypt.h
main.c
tcp_request.c
udp_request.c

By default, dnscrypt-wrapper forwards non-dnscrypted queries to the upstream server.
But people may want to run a service that only accepts authenticated queries. Some might think that this is already the case and don't know that the dnscrypt port can also work with regular DNS queries.
And to accept both regular and dnscrypted queries, the easiest, fastest and safest way is to use different ports.
This pull request refuses unauthenticated queries by default, and introduces a new switch, `-U`, to explicitly allow them if needed.

Add a new switch to explicitly allow unauthenticated queries

---

Makefile

I've been working on adding this project to the FreeBSD Ports Collection. During this, I found that the install path prefix being hard-coded to /usr/local in Makefile breaks the port build. This is because the port is first made in a working directory before installation or packaging. The FreeBSD Porter's Handbook [speaks in detail](https://www.freebsd.org/doc/en_US.ISO8859-1/books/porters-handbook/porting-prefix.html) about this issue and advises inheriting $PREFIX from the environment. So, I'm suggesting a change where $prefix will be set to $PREFIX if the latter is present, otherwise it is set to "/usr/local" as before.

Inherit install path from environment if present

---

README.md
example/start_wrapper.sh
main.c

So that the tool can be used to generate keys and certificates of any names.
Also provide default values (the same as before) for everything.

Remove hardcoded file names

---

example/start_proxy.sh
example/start_wrapper.sh
test.sh

A minimal shell is totally fine.
Bash is not installed by default on BSD systems, and when it is, it's not
as /bin/bash. It is not always present in Docker containers either.

Bash is not required to run these scripts.

---

.travis.yml
dnscrypt.c
dnscrypt.h
main.c
tcp_request.c
udp_request.c

Accept multiple keys.
I still need to update the README file, but here is how to seamlessly switch to a new key:
1) Create the first key and its related certificate:
$ dnscrypt-wrapper --gen-crypt-keypair --crypt-secretkey-file=1.key
$ dnscrypt-wrapper --gen-cert-file --crypt-secretkey-file=1.key --provider-cert-file=1.cert
Run the server:
$ dnscrypt-wrapper --resolver-address=114.114.114.114 \
--provider-name=2.dnscrypt-example.org \
--listen-address=0.0.0.0:443 \
--crypt-secretkey-file=1.key \
--provider-cert-file=1.cert
2) Before 1.key expires, create a fresh new key and a certificate for it:
$ dnscrypt-wrapper --gen-crypt-keypair --crypt-secretkey-file=2.key
$ dnscrypt-wrapper --gen-cert-file --crypt-secretkey-file=2.key --provider-cert-file=2.cert
Run a new instance of the server, …

Support for multiple keys / seamless key rotation

---

main.c

Display what's going on when public.key/secret.key cannot be loaded

---

main.c

It might be useful to retrieve the provider publickey fingerprint so that you don't have to remember it or write it somewhere.

Add --provider-publickey-fingerprint switch

---

Makefile

Example:
make configure
./configure --prefix=/usr
make
make install DESTDIR=/tmp/dnscrypt-wrapper

Allow dnscrypt-wrapper to be installed into another DESTDIR

---

README.md

I created a FreeBSD port of dnscrypt-wrapper and it has been accepted to the official ports tree, so it is can now be installed much more easily. More info here: http://www.freshports.org/dns/dnscrypt-wrapper

Updated FreeBSD installation instructions

---

debug.c

There was no `return` statement on Linux systems that were not x86 or x86_64.

debug: still return something on non-Intel Linux systems

---

udp_request.c
udp_request.h

This is part of the second version of the protocol, is supported by the client since dnscrypt-proxy 1.3.3, and prevents DNS amplification attacks.

Send a short packet with TC set if the query_len < response_len

---

cert.c

...instead of a fixed serial.
A fixed serial number was fine, but when multiple valid certificates are
found for the current date, the one with the highest serial number is
preferred. Which is usually what people want when they update the
certificates for whatever reasons.

Use the certificate timestamp as a serial number

---

Makefile
argparse/Makefile

- Make flags always overridable by user ({C,LD}FLAGS ?=)
- Move customizable bits (```-O*```, ```-g*```) into default CFLAGS/LDFLAGS, and leave mandatory ones in BASIC_{C,LD}FLAGS
- Apply BASIC_{C,LD}FLAGS before {C,LD}FLAGS, because the latter may
contain e.g. additional -I/-L paths and these should come after local
ones such as ```-I./argparse```

Fix compiler/linker flags handling

---

COPYING

The license of dnscrypt-proxy and dnscrypt-wrapper are exactly the same, so just keep the one from dnscrypt-wrapper.
Also, salsa20_random and other crypto operations are not part of this package any more.

Remove duplicates/obsolete parts

---

main.c

Not sure if this is obsolete, some providers have a record, some don`t.

Add switch to allow printing of encoded .crt for an appropriate TXT

---

main.c

dnscrypt_key_to_fingerprint was not offseting the key based on
keypair_id resulting in always fingerprinting the first key in the list.
```
vagrant@vagrant:/vagrant$ sudo ./dnscrypt-wrapper
--resolver-address=127.0.0.1:53 --listen-address=0.0.0.0:8443
--provider-name=2.dnscrypt-cert.example.com
--crypt-secretkey-file=keys1/1.key,keys2/1.key
--provider-cert-file=keys1/1.cert -VVVVV
[2465] 18 Nov 07:15:49.137 [info] [main.c:417] Crypt public key
fingerprint for keys1/1.key:
4F9D:075B:7336:7196:80A9:104A:3563:44ED:F23A:FA30:0555:CBA1:9284:8529:6A73:2E2F
[2465] 18 Nov 07:15:49.138 [info] [main.c:417] Crypt public key
fingerprint for keys2/1.key:
4F9D:075B:7336:7196:80A9:104A:3563:44ED:F23A:FA30:0555:CBA1:9284:8529:6A73:2E2F
```
```
vagrant@vagrant:/vagrant$ sudo ./dnscrypt-wrapper …
```

Fix crypt public key fingerprint log.

---

dnscrypt.c
dnscrypt.h
tcp_request.c
udp_request.c

cert distribution code for UDP and TCP was duplicated. This refactors the code that deals with creating the DNS response into a separate function, letting the UDP/TCP code path deal with the transmission only.

refactor `self_serve_cert_file` to only use a common `dnscrypt_self_serve_cert_file` for both UDP and TCP.

---

dnscrypt.h
main.c
tcp_request.c
udp_request.c

There is cases where it may be desireable to bind the source address of
outgoing connections.
This diff adds support for it.
When using UDP, this will cause the outgoing connection to listen on
IP:port vs *:port.
When using TCP, the outgoing connection is going to use the provide IP
vs letting the OS do it.
Tested by running a local unbound instance. When not binding to eth0 IP,
connections would be coming from 127.0.0.1, when using
--outgoing-address, connections would be coming from the provided IP.
Likewise with ipv6, tested using --outgoing-address=[::1] against a
resolver listening on ::1 and --outgoing-address=[::1]:portnumber.
This confirmed we would indeed bind to the provided port. Binding to 1
specific port for outgoing connection is not desirable, but provided
users only …

Allow binding outgoing address

---

debug.c

fix compile with cygwin64 error

---

dnscrypt.c
dnscrypt.h
main.c
tcp_request.c
tcp_request.h
udp_request.c
udp_request.h

this should start using the changes from #105 to find the right keypair based on the cert used by the client.

Xchacha20 fixes

---

README.md
dnscrypt.h
main.c
version.h

dnscrypt-proxy 2.0 can extract server parameters from a single string ("stamp").
A stamp includes the protocol name (so it will also work with DNS-over-HTTP2, and even with open resolvers that don't support encryption), informal data about the server (support for DNSSEC and nologs), as well as the public key and other parameters for the chosen protocol.
So, there's only one string to copy&paste to use a server.
A server can be presented as a random description for humans, and a stamp anywhere in the description, that will be used by non-humans :)
So, this pull request simply prints the stamp, along with legacy things for version 1.

Add support for stamps (dnscrypt-proxy 2.x); update the documentation

---

dnscrypt.c

Oops, the cache didn't play well with multiple keys being used simultaneously :)
My bad. This fixes it.

cache: do not forget to include the server PK in the hash computation

---

cert.c
cert.h

I was very confused by the values in the `SignedCert` structure, that looked all wrong. The magic didn't match the public key, the timestamps were in year 1977 ...
Everything was shifted by 64 bytes due to the missing signature. There was 64 extra bytes at the end of the structure to compensate for that, but after the signature, the fields didn't match their initial value any more.
Anyway, this includes the signature in the structure, removes the 64 bytes at the end, and greatly simplifies the code. `unsign` was removed as well as it wasn't used anywhere.

Include the signature in SignedCert

---

dnscrypt.c
tcp_request.c
udp_request.c

The missing checks after uncurve() don't seem to have any implications since the buffer has a fixed length.
The unpadding code may allow an attacker to cause a remote DoS though. This is not good.

Add missing checks

---

dnscrypt.c
dnscrypt.h
main.c
version.h

- find_cert() should search in all certs.
- filter_signed_certs() should convert serial to uint32_t before comparison.

Fixes multiple certs issue

---

tcp_request.c
udp_request.c

_dnscrypt-wrapper_ in [dnscrypt-server-docker](https://github.com/jedisct1/dnscrypt-server-docker) produces hundreds messages of
> [warning] [udp_request.c:302] Short query received
in the Docker logs.
In my opinion that's not a warning, so output them only in debug.

Log level of "Short query received" changed to debug
